### ISSUE TITLE
Make the writer context pull the type from the field instead of pulling it from the actual object

### ISSUE THREAD

**Issue by knightzmc** [Sxtanna/korm#5]
supposedly it's a good idea so do it 

![image](https://user-images.githubusercontent.com/18754735/75722205-a5ee4e80-5cd1-11ea-86dd-d7585859877d.png)

**Comment by Sxtanna** [comment]
I honestly have no idea what my brain was thinking when it came to that conclusion.

I implemented it on another branch, and honestly I don't think it would be a good idea anymore xD

https://github.com/Sxtanna/korm/blob/write_field_type/src/test/kotlin/com/sxtanna/korm/TestWriter.kt#L29
